### PR TITLE
add basic eks cluster example

### PR DESCRIPTION
**Pull request by sean1588**
related to: https://github.com/pulumi/pulumi-eks/issues/1048

Adds a basic example to the eks cluster resource page, since this page is missing examples. I took this from the pulumi-eks guide: https://www.pulumi.com/docs/clouds/aws/guides/eks/

I also added in the missing descriptions text for the [CoreData](https://www.pulumi.com/registry/packages/eks/api-docs/cluster/#coredata) nested type.

Screenshot from 2024-04-01 15-03-06

### CODE REVIEW

**Comment by blampe** [comment]
@sean1588 I think you'll need to update the docstring [here](https://github.com/pulumi/pulumi-eks/blob/master/provider/cmd/pulumi-gen-eks/main.go#L152-L154) instead of in `schema.json`, and then you'll need to regenerate SDKs to reflect the new description. Running `make` (after you update `main.go`) should do the trick.

**Comment by sean1588** [comment]
ahhh ok that makes sense. thanks so much @blampe!

**Comment by sean1588** [comment]
thanks @blampe, I updated to move the docs string to the main.go file. I also added in the missing descriptions for the [CoreData](https://www.pulumi.com/registry/packages/eks/api-docs/cluster/#coredata) supporting type.

**Comment by mjeffryes** [comment]
Looks like this is really close, but we still need to generate java and nodejs SDKs

**Comment by blampe** [comment]
Looks like a flake, re-running.

> error downloading provider aws to file: failed to download plugin: aws-6.0.4: write /tmp/pulumi-plugin-tar1375576335: no space left on device

**Review by blampe — APPROVED** [review]
Thanks for this improvement!

I didn't look closely at the example, but if it matches what's in the guide then it's probably fine.

It would be nice to be able to more easily keep these docstrings in sync with examples like that, but we don't need to solve that here.

**Comment by sean1588** [comment]
Thanks @blampe!! Yeah I took the example straight from the guide, but yeah would be great if we had a way to keep these in sync.

**Pull request merged**
