### PR TITLE
Re-apply "expose ipFamily"

### LINKED ISSUE #698: Add support for ClusterKubernetesNetworkConfig-> ipFamily to support IPv6
We need to add support for [ClusterKubernetesNetworkConfig-> ipFamily](https://www.pulumi.com/registry/packages/aws/api-docs/eks/cluster/#clusterkubernetesnetworkconfig)

_Originally posted by @davidroth in https://github.com/pulumi/pulumi-eks/issues/675#issuecomment-1106453162_

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Re-applies pulumi/pulumi-eks#882 to fix #698 but now with green build (eventually)

### CODE REVIEW

**Comment by AnticliMaxtic** [comment]
I would like to be able to use this feature, but I unfortunately don't think I have the skills to fix what needs done for the tests, but if there is some way I can help I can try.

**Comment by PrpAcline** [comment]
@mikhailshilkov is there anything else that needs to be done other than a review? Happy to contribute if there is anything I can do.

**Comment by davidroth** [comment]
@mikhailshilkov Waiting for this since many years. Any ETA possible?

AWS is now charing for IPV4 making this even more important: https://aws.amazon.com/blogs/aws/new-aws-public-ipv4-address-charge-public-ip-insights/

**Comment by rquitales** [comment]
Superseded by #1098

**Pull request closed without merging**
