### PR TITLE
Temporarily pin kubectl version

### PR DESCRIPTION
**Pull request by viveklak**
### Proposed changes
Pin the kubectl version to 1.23.6 to temporarily workaround https://github.com/aws/aws-cli/issues/6920 to fix CI runs.

### CODE REVIEW

**Review by guineveresaenger — APPROVED** [review]
reminder to create an issue to track unpinning

**Review by stack72 — COMMENTED** [review]
Do we need this in master and release?

**Comment by viveklak** [comment]
> 

Sounds like we do, yes. I initially grepped for kubectl but it looks like these workflows do run the tests as well and might be using the base image's kubectl. Which according to this is 1.24.0: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

**Comment by yasinntza** [comment]
@viveklak  how can I fix this issue for myself. I am still getting this error. I added github workflow and error image

Screen Shot 2022-05-09 at 19 20 22

image
?

**Comment by viveklak** [comment]
@yasinntza the fundamental problem here was that aws-cli was lagging on picking up the deprecation of the above api version. That seems to have just been fixed: https://github.com/aws/aws-cli/issues/6920. I will be looking to revert this PR shortly.

**Comment by AaronFriel** [comment]
Hey, thanks for the issue report. 1.24 deprecations are definitely an issue people can face with Kubernetes, but I think I'm missing a couple pieces of the puzzle. I have a couple questions:

1. Are you using a self-hosted runner or one of GitHub's runners (GitHub defaults to their virtual environments.) If the latter, it looks like their runners recently updated to 1.24.0, which would be out of our hands. https://github.com/actions/virtual-environments

2. Are you executing any kubectl commands directly or providers other than EKS?

**Pull request merged**
