### PR TITLE
Schematize remaining surface area

### PR DESCRIPTION
**Pull request by justinvp**
- Expose `VpcCni` resource
- Expose `NodeGroup` component
- Expose `Cluster.storageClasses`
- Expose external types/resources from AWS and Kubernetes
- Expose functions as components:
    - `createManagedNodeGroup` => `ManagedNodeGroup` component
    - `createNodeGroupSecurityGroup` => `NodeGroupSecurityGroup` component
    - `getRoleProvider` => `ClusterCreationRoleProvider` component

I'll open a separate PR with examples (tests).

Fixes https://github.com/pulumi/pulumi-eks/issues/454
Fixes https://github.com/pulumi/pulumi-eks/issues/452

### CODE REVIEW

**Comment by justinvp** [comment]
@lblackstone, would you mind taking a look at this PR? I'd love to get this initial cut of the surface area merged into master today. I've updated this PR to use the latest releases of pulumi, aws, and kubernetes SDKs. I'll open a follow-up PR with examples and get them hooked up to run as tests.

**Review by lblackstone — APPROVED** [review]
I didn't check everything exhaustively, but it looks good AFAICT

**Comment by lukehoban** [comment]
:tada:

**Pull request merged**
