### PR TITLE
Upgrade aws-k8s-cni to v1.7.5

### PR DESCRIPTION
**Pull request by stack72**
Fixes: #453

### CODE REVIEW

**Comment by stack72** [comment]
This file is taken from https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.7.5/config/v1.7/aws-k8s-cni.yaml

**Comment by leezen** [comment]
I'm not 100% sure how to review this at this point. Is there any divergence between what we want in the manifest vs. what's default to AWS? For a while, there was the divergence with fargate in https://github.com/pulumi/pulumi-eks/pull/291 but that divergence disappeared a year ago in https://github.com/aws/amazon-vpc-cni-k8s/pull/792 -- is there any else materially different that should be preserved?

**Comment by emiioan** [comment]
Any updated on this? We just upgraded our eks clusters to 1.16 and we are using for now a fork and override the yaml file with 1.7.5 version but we will really want to use the upstream librabry. Also double check yaml compute function because for now if you provide  vpcCniOptions:   { warmIpTarget: 2}, env var "WARM_IP_TARGET" is not picked up by cni Daemonset.

**Review by leezen — APPROVED** [review]

**Comment by emiioan** [comment]
Hello, when should we expect to have this merged into master branch?

**Pull request merged**
