### PR TITLE
Tracking a change to pulumi-aws that adds support for Node Spot Groups

### PR DESCRIPTION
**Pull request by stack72**
This is a breaking change of sorts but is a required for further node group work

### CODE REVIEW

**Review by lblackstone — APPROVED** [review]
Change LGTM, but curious where the functional change was made. It seems like we should be able to support either input shape.

**Comment by stack72** [comment]
The change is in pulumi-aws which feeds back to TF

**Review by justinvp — APPROVED** [review]
LGTM

I was wondering about `instanceTypes`...

https://github.com/pulumi/pulumi-eks/blob/c0548fd03abe0bb24b9e8d33cb18e09872c82ad0/provider/cmd/pulumi-gen-eks/main.go#L581-L589

I'll update https://github.com/pulumi/pulumi-eks/pull/475 to project it as an array to match the updated AWS signature.

**Pull request merged**
