### PR TITLE
catch up to master

### PR DESCRIPTION
**Pull request by houqp**
This PR syncs decompose branch with master

### CODE REVIEW

**Comment by houqp** [comment]
Quick question, currently, eksNodeAccess is created inside workerpool module, which means there will be one such config map created for each pool. Is this the preferred behavior?

**Comment by houqp** [comment]
Yes, that's what I have in mind as well. Will make the change later today.

**Comment by houqp** [comment]
Ok, I have moved eksNodeAccess config map into core.

**Comment by houqp** [comment]
Thanks for the review, what's the process for getting this merged into master? Do we need to work on unit tests?

**Comment by pgavlin** [comment]
You can open a PR from the `pgavlin/decompose` branch into master and we can take it from there :)

**Pull request merged**
