### PR TITLE
Enable integration tests to retry failed steps

### PR DESCRIPTION
**Pull request by metral**
### Proposed changes

- deps: bump to latest pulumi/pulumi v1.6.1
- tests: enable RetryFailedSteps for all tests

### CODE REVIEW

**Comment by metral** [comment]
> I assume there are not any issues due to recent Pulumi/Pulumi using Go 1.13 and this rep using Go 1.12?

Not that I'm aware of. But i've opened an issue to track this update: https://github.com/pulumi/pulumi-eks/issues/289

**Comment by metral** [comment]
Actually, CI is hitting this. Not sure if its related to go 1.13. 

cc @pgavlin @stack72 

> github.com/pulumi/pulumi-eks/nodejs/eks/examples
package github.com/pulumi/pulumi-eks/nodejs/eks/examples (test)
	imports github.com/pulumi/pulumi/pkg/testing/integration
	imports github.com/pulumi/pulumi/pkg/backend/filestate
	imports github.com/pulumi/pulumi/pkg/backend
	imports github.com/pulumi/pulumi/pkg/backend/display
	imports github.com/pulumi/pulumi/pkg/resource/stack
	imports github.com/pulumi/pulumi/pkg/secrets/cloud
	imports gocloud.dev/secrets/azurekeyvault
	imports github.com/Azure/go-autorest/autorest: cannot find package "github.com/Azure/go-autorest/autorest" in any of:
	/home/travis/gopath/src/github.com/pulumi/pulumi-eks/vendor/github.com/Azure/go-autorest/autorest (vendor tree)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/github.com/Azure/go-autorest/autorest (from $GOROOT)
	/home/travis/gopath/src/github.com/Azure/go-autorest/autorest (from $GOPATH)
FAIL	github.com/pulumi/pulumi-eks/nodejs/eks/examples [setup failed]
Makefile:30: recipe for target 'test_all' failed
make[1]: *** [test_all] Error 1
make[1]: Leaving directory '/home/travis/gopath/src/github.com/pulumi/pulumi-eks/nodejs/eks'
build/common.mk:195: recipe for target 'nodejs/eks_all' failed
make: *** [nodejs/eks_all] Error 2
The command "make travis_${TRAVIS_EVENT_TYPE}" exited with 2.

**Comment by pgavlin** [comment]
> `imports github.com/Azure/go-autorest/autorest: cannot find package "github.com/Azure/go-autorest/autorest"`

Generally this can be fixed using a `replace` directive in `go.mod`. For example, in `pulumi/pulumi`'s `go.mod`, we have this:

```
replace github.com/Azure/go-autorest => github.com/Azure/go-autorest v12.4.3+incompatible
```

I think adding that to this repo's `go.mod` and running `make ensure` should do the trick.

**Comment by metral** [comment]
Hitting the following after running the suggestion in https://github.com/pulumi/pulumi-eks/pull/288#issuecomment-562412238, and then doing a `go get github.com/pulumi/pulumi@master && make ensure` (latest commit)

```
ENSURE:
GO111MODULE=on GOPROXY='https://proxy.golang.org' go mod tidy
GO111MODULE=on GOPROXY='https://proxy.golang.org' go mod vendor
error: working tree is not clean, aborting!
HEAD detached at FETCH_HEAD
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
	modified:   go.sum
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	packages-microsoft-prod.deb
no changes added to commit (use "git add" and/or "git commit -a")
diff --git a/go.sum b/go.sum
index d0863dd..e54bb39 100644
--- a/go.sum
+++ b/go.sum
@@ -411,6 +411,7 @@ golang.org/x/tools v0.0.0-20190312170243-e65039ee4138/go.mod h1:LCzVGOaR6xXOjkQ3
 golang.org/x/tools v0.0.0-20190422233926-fe54fb35175b h1:NVD8gBK33xpdqCaZVVtd6OFJp+3dxkXuz7+U7KaVN6s=
 golang.org/x/tools v0.0.0-20190422233926-fe54fb35175b/go.mod h1:LCzVGOaR6xXOjkQ3onu1FJEFr0SW1gC7cKk1uF8kGRs=
 golang.org/x/tools v0.0.0-20190506145303-2d16b83fe98c/go.mod h1:RgjU9mgBXZiqYHBnxXauZ1Gv1EHHAz9KjViQ78xBX0Q=
+golang.org/x/tools v0.0.0-20190606124116-d0a3d012864b h1:mSUCVIwDx4hfXJfWsOPfdzEHxzb2Xjl6BQ8YgPnazQA=
 golang.org/x/tools v0.0.0-20190606124116-d0a3d012864b/go.mod h1:/rFqwRUd4F7ZHNgwSSTFct+R/Kf4OFW1sUzUTQQTgfc=
 golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7 h1:9zdDQZ7Thm29KFXgAX/+yaf3eVbP7djjWp/dXAppNCc=
 golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
The command "${PULUMI_SCRIPTS}/ci/ensure-dependencies" failed and exited with 1 during .
```

@pgavlin @stack72 any ideas?

**Comment by stack72** [comment]
@metral fixed - there seems to be a problem where x/tools doesn't get added to the go.sum file on *some* package references. It just needed to be manually added

**Comment by metral** [comment]
Thanks @stack72 🎉

**Pull request merged**
