### PR TITLE
fix: correct spelling for encryptRootBlockDevice

### LINKED ISSUE #446: encryptRootBockDevice should be Block instead of Bock
File: [docs/reference/pkg/nodejs/pulumi/eks/_index.md](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/eks/)
property encryptRootBockDevice should be Block instead of Bock

### PR DESCRIPTION
**Pull request by metral**
### Proposed changes

fix: correct spelling for encryptRootBlockDevice

### Related issues (optional)

Fixes #446

### CODE REVIEW

**Comment by stack72** [comment]
this is a breaking change right? Can we do it in a way where we deprecate the old and point to the new and then be able to take them into account?

**Comment by metral** [comment]
@stack72 Thanks for input. PTAL

**Review by stack72 — APPROVED** [review]
this is awesome! thanks

**Pull request merged**
